### ISSUE TITLE
eventbrite replacement - payments

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#10]
as discussed, there are issues with eventbrite.  the issue focus is on payments.  the payments issue has to do with eventbrite's payment policy, which directly impacts cash flows.

jan mentioned Stripe.
joel mentioned Paypal.

Can we get a couple more potentials so I can do business analysis on the options.

thanks

**Comment by jberger** [comment]
For the record I have no attachment/experience with PayPal other than
knowing it exists.

**Comment by rpcme** [comment]
duly noted.

Even though jan has worked with stripe, I also don’t take that as endorsement.

**Comment by jhthorsen** [comment]
I've heard it can be difficult to get money from PayPal, if the amount gets higher than a (unknown) threshold. It might not be that way anymore, but it used to be. So PayPal is nice for small transactions, but probably not for a conference.

I've not worked with Stripe. I've only made the integration and registered an account. @marcusramberg has worked with Stripe though, but not with my plugin.

I think we should not only focus business analysis but also on which payment solution we can integrate with easily.

I got these modules:
- Mojolicious::Plugin::PayPal (on cpan and used by others)
- Mojolicious::Plugin::StripePayment (not yet on cpan, but tested locally)

**Comment by tempire** [comment]
Stripe is MUCH easier to work with than PayPal. By a billion orders of
magnitude. It also has more respect from the dev community, and a much
easier purchasing flow.

If I know an organization uses Stripe, I respect them more. If I see them
using PayPal, I tend to believe they don't know what they're doing.

**Comment by rpcme** [comment]
Agreed.  Those are functional requirements, and I appreciate any you have in mind.

**Comment by rpcme** [comment]
thanks for the feedback

do you know of other payment system vendors?

**Comment by tempire** [comment]
Those are the only two payment options I'm aware of.

**Comment by rpcme** [comment]
There's actually many others. WePay and Propay are good.  but maybe not as hipster/trendy as stripe, but I don't care one bit about hipster value.

Anyways, I have to consider the on-site merchandising so if the same provider does online as well as bricks n mortar it is better positioned as a winner.

**Comment by rpcme** [comment]
This has been decided and stripe has been implemented.
