### ISSUE TITLE
Fix mojoconf.org

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#11]
@tempire: I think we need to move mojoconf.org back to where it was. We're messing up all old links the way it is now.

I will assign this to @ssm, unless you disagree.

We can move the DNS record later on if needed. I will add a big button to mojoconf.org which sends the visitor to mojoconf.com.

I will later on (when I have gotten in touch with ACT) be able to move mojoconf.org back to you, but then you have to be ready with this redirect:

``` perl
$app->hook(
  before_dispatch => sub {
    my $c = shift;
    my $url = $c->req->url->path;

    if ($path->[0] and $path->[0] eq 'mojo2014') {
      $c->redirect_to("http://act.yapc.eu/mojo2014/$path");
    }
  },
);
```

**Comment by tempire** [comment]
Do we really care about old content more than having both domains work as
most people would expect?

**Comment by jhthorsen** [comment]
Yes. I want to visit my old profile page.

**Comment by jhthorsen** [comment]
@ssm: can you temporarily move the domain back? I think the ip is 91.216.186.189 (if you don't already know)

**Comment by jhthorsen** [comment]
I've added this to the 2014 ACT page:

```
Revision: 105
Author:   jhthorsen
Date:     2015-03-04 20:21:47 +0100 (Wed, 04 Mar 2015)
Log Message:
-----------
Add link to 2015

Modified Paths:
--------------
    actdocs/static/index.html

Modified: actdocs/static/index.html
===================================================================
--- actdocs/static/index.html   2015-02-27 21:24:34 UTC (rev 104)
+++ actdocs/static/index.html   2015-03-04 19:21:47 UTC (rev 105)
@@ -2,6 +2,16 @@

 <div class="row with-air">
   <div class="col-sm-8">
+    <h2>Mojoconf 2015</h2>
+    <p class="alert alert-info">
+      <a href="http://mojoconf.com/">Mojoconf 2015</a> is
+      <a href="http://blog.kraih.com/post/112617736601/mojoconf-2015">announced</a>.
+      <br>
+      <a href="http://mojoconf.com/" class="btn btn-primary btn-lg">Go to Mojoconf 2015</a>.
+    </p>
+  </div>
+
+  <div class="col-sm-8">
     <h2>23rd to 25th of May, 2014</h2>

     <p>
```

**Comment by jhthorsen** [comment]
Nevermind. I totally forgot about the "Host" header! Will push a "fix" to MCT soon.

**Comment by jhthorsen** [comment]
Fixed in https://github.com/mojoconf/MCT/commit/cbd61b534a3a111ef0f471d034401335032c6001

**Comment by jhthorsen** [comment]
@tempire: Please reload the webserver with the new code and close this issue after you have verified that http://www.mojoconf.org/mojo2014/ does not result in 404.
