### ISSUE TITLE
Mojoconf 'theme'

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#13]
Best themes are positive and forward-looking.  A theme directly impacts marketing collateral, sponsor co-marketing, and general perceptions by attendees.

For this kind of project, I would like to make it seem like Mojolicious is like turning a corner.  A corner that's transformative.  A corner that makes your heart start racing because you can't keep up with all the possibilities going through your head.

My take on this is a futuristic, global, perhaps even foreign theme. One that's going to jolt people from the start of the conference, but they gel with its vibe by the end.

I would like others to drop notes on their thoughts on this before I start short-listing.

**Comment by rpcme** [comment]
Okay I really would like people to comment on this.

Otherwise, I might just make the theme song this, which surely is not the best choice:

https://www.youtube.com/watch?v=UoK8DaJRDaM

**Comment by tempire** [comment]
If we're going this route, this is the song. I meant to use this song km
last year, but didn't see an opportunity.

https://m.youtube.com/watch?v=eWM2joNb9NE

**Comment by rpcme** [comment]
Ok, I think those two are squarely in the "bottom two".

**Comment by rpcme** [comment]
I think we will skip the theme action.
