### ISSUE TITLE
Stripe test snippet

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#15]
The snippet for stripe payments is at https://github.com/mojoconf/nyc-2015-06-05/tree/master/payments

Please let me know if you require anything else from me.

Perhaps we need to be online at the same time so I can verify payments via the dashboard.

Thanks very much!

**Comment by jhthorsen** [comment]
This is handled in https://github.com/mojoconf/MCT/pull/42
