### ISSUE TITLE
Strategy for moving users from Eventbrite

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#16]
We have a number of registered users on eventbrite.

we need a strategy to get their profile initialized and tapped as paid on the MCT site.

**Comment by jhthorsen** [comment]
Do you mean that you want them registered in the MCT database as if they had gone through the stripe payment?

**Comment by rpcme** [comment]
Yes, because there shouldn't be any confusion whether or not they've paid.

It should be a one-off, and perhaps as simple as asking them to register, and then flip the paid 'bit'.

**Comment by jhthorsen** [comment]
I can fix this manually in the database. Let's keep the issue open until we get stripe in place.

**Comment by rpcme** [comment]
Good.  When we are ready to go live, we have to coordinate to "turn off" eventbrite, get a list of those who have registered on eventbrite, ask them to register on mojoconf, and then we can flip the bit.

**Comment by rpcme** [comment]
Closed.  It's all up and running now.
