### ISSUE TITLE
Need to document what happens on each day

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#17]
From http://irclog.perlgeek.de/mojo/2015-03-23#i_10326153:

```
confusing mojoconf is confusing
site says 4-6th, yet "conf day" is listed as 5th only
am I missing an obvious link?
```

I think we need to add a "schedule" on the landing page describing what happens on each day.

**Comment by rpcme** [comment]
Yes, that is why I put this in repository:

nyc-2015-06-05/schedule.org http://schedule.org/

If you would like to post 
- training day (4th)
- presentation day (5th)
- hackathon day  (6th)

pop it in test, i will take a look and then we can push to prod

I think I mentioned this in IRC but no one took notice...

thanks

**Comment by jhthorsen** [comment]
I really have no idea how the wording should be. I was thinking about adding the dates after the headings, but we don't have anything for "Hackathon".

**Comment by rpcme** [comment]
Updated, please look at 2nd major heading section of https://github.com/mojoconf/nyc-2015-06-05/blob/master/schedule.org

**Comment by rpcme** [comment]
This has been clarified on the landing page
