### ISSUE TITLE
sponsorship pages on mojoconf.com

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#18]
Hello 

We require a section on landing page re: sponsorships, placeholder for two sponsor logos, and sponsorship link in menu

the sponsorship menu link takes you to the sponsorship page listing all corporate and individual sponsors.

We will need to have this posted:

https://github.com/mojoconf/nyc-2015-06-05/blob/master/mktg/prospectus.pdf

And this is some "starter text" for the content.  recommendations welcome.

https://github.com/mojoconf/nyc-2015-06-05/blob/master/mktg/sponsorship.org

**Comment by jhthorsen** [comment]
Where do you want prospectus.pdf posted? As a download link..? Where? In what format?

**Comment by rpcme** [comment]
Has to be download link in PDF format.  Take file as-is.

**Comment by rpcme** [comment]
Link on sponsorship page -- subpage not landing page
