### ISSUE TITLE
When are the training classes?

### ISSUE THREAD

**Issue by briandfoy** [mojoconf/nyc-2015-06-05#19]
Because some one asked me:

https://twitter.com/mnlagrasta/status/583698034418028544

**Comment by tempire** [comment]
Added a cursory schedule to the landing page, and a blurb on the training summary page about the dates.

https://mojoconf.com/ https://mojoconf.com/

**Comment by briandfoy** [comment]
Awesome (although I might add the date next to or instead of "Day 1"). Still, now I can answer the question!
