### ISSUE TITLE
Website coordinators

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#2]
@tempire is main website coordinators, with me and @jberger as backup.

We have created the [MCT](https://github.com/mojoconf/mct) project. This project will integrate with https://eventbrite.com, but also need talk admin page.

It also needs to look shiny of course :smile:

**Comment by jhthorsen** [comment]
We need the site to be official before 2015-03-07 and talk submission need to be working the same time.

**Comment by rpcme** [comment]
We have closed this responsibility.
