### ISSUE TITLE
mojoconf.com: Admin > Purchases 'Captured' link

### ISSUE THREAD

**Issue by rpcme** [mojoconf/nyc-2015-06-05#24]
The Captured link points to test dashboard, not live dashboard.  In such case, a 404 is returned.

Please change: 

test => ""

meaning:

https://dashboard.stripe.com/test/payments/(token)
->
https://dashboard.stripe.com/payments/(token)

**Comment by jhthorsen** [comment]
This looks like a duplicate of https://github.com/mojoconf/MCT/issues/62
