### ISSUE TITLE
Mojo artwork and license

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#4]
@rpcme need a written license for the artwork. Maybe @jberger can get this information from sri?

@rpcme says: "I need to make sure the wording is commercial/non-commercial use, etc."

Would be nice if the artwork was also attached and/or linked to from this issue.

**Comment by kraih** [comment]
Which artwork specifically?

**Comment by rpcme** [comment]
Not chosen yet.  But the intention is to do merchandising, both conference-ware and mojo-ware (like what you can buy linked from mojolicio.us).  It is probably most practical to have the stuff made stateside.  Also I thought that someone, like jberger if he so desires, can take leftover mojo-ware to YAPC::NA.

A question I asked also was if it is if you required royalty on that, and if so your expected percentage.  If we can't make margin on 60/70% of stock cleared then it may just be skipped.

**Comment by kraih** [comment]
As long as it's limited to the conference i do not expect royalties, but please don't replicate the exact same design that's used by the shirts on mojolicio.us. So, i hereby grant the organizers permission to use the Perl5 Raptor and Mojolicious Pirate Cloud on marketing material and conference shirts for Mojoconf 2015 New York, without the attribution requirements of the original license.
