### ISSUE TITLE
Decide on pre-conference meetup

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#6]
We need to know when the pre-conference is, when and where. We also need someone to be there at a given time.

**Comment by tempire** [comment]
What's intended purpose? Planning? Sponsors?

**Comment by rpcme** [comment]
nope.  it's like last year, just a pre-conference/post-training networking event. thurs night.

I would like to scrape enough dough together to give drink tickets this year though.  I will budget for it and see how far we get.

**Comment by rpcme** [comment]
But, I do know of a pretty awesome tequila bar downtown manhattan.  and there's an awesome sake bar in the basement on e 43rd.

**Comment by tempire** [comment]
Wherever it is, it should have non-alcoholic options.

**Comment by rpcme** [comment]
of course, it's virtually the law.
