### ISSUE TITLE
20 things why....

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#7]
Need input on this @rpcme, @marcusramberg, @jberger, @tempire.

Questions:
1. 20 things why people would only use mojolicious over anything else
2. 20 things why mojoconf is a must attend event for web developers, designers

**Comment by tempire** [comment]
What is this going to be used for? In what format will it be presented?

**Comment by rpcme** [comment]
inbound marketing messaging.  twitter.  keep it short and sometimes humorous would be nice.

if you guys come up with good ones, they could be used elsewhere or built upon.

**Comment by tempire** [comment]
Easy non-blocking syntax in contiguous steps with Mojo::IOLoop::Delay

**Comment by tempire** [comment]
Serve 1000s of requests with one process

**Comment by jhthorsen** [comment]
I'm no good at "oneliners", but I have som ideas:
- How many concurrent websockets can mojo hande in one process now...? Was it 20k on a regular laptop?
- Another cool think is how good mojo is in regards of standards, and how fast sri is to implement the changes. Thinking about WebSockets, JSON, HTTP, ...

**Comment by rpcme** [comment]
very good start
I will start collating them this evening in a file

**Comment by jberger** [comment]
Of course I'm one for the non-blocking stuff, but we should get some of the easy ones too.
- Super easy to install
- Consistent interface design
- Has a vibrant community
- Has lots of community created plugins on CPAN
- Has a very powerful (dare I say best?) web testing library
- The UserAgent and DOM parser make scraping a breeze

etc

**Comment by rpcme** [comment]
Completely agreed!!

they can also be snarky/humorous but not offensive ….

**Comment by marcusramberg** [comment]
Mojoconf 2015 in The Big Apple - Yeah Baby, Yeah.
