### ISSUE TITLE
Set up a mailinglist and contact email account

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/nyc-2015-06-05#8]
We need somewhere people can send emails. Some of the messages people want to send is not for the public, so Mojolicious Mailing List won't work.

I'm suggesting that I set up "mojoconf.com" in my google apps account, and @tempire update the MX records.

After that I can register an alias contact@mojoconf.com which I forward to @rpcme and @tempire (?)

What do you think?

**Comment by tempire** [comment]
hello@mojoconf.com

This is a common help address these days, and it's fun.

**Comment by jhthorsen** [comment]
That's cool. Then you can close this issue after you have updated the contact links on the webpage.

**Comment by tempire** [comment]
Mx records added.

**Comment by jhthorsen** [comment]
@tempire: I have no idea what you're doing. Mx records added...? To what/which server?

The reason why I'm confused is that my initial question "What do you think?" has not been answered. Are you doing your own thing, or should I set up google apps..?

**Comment by rpcme** [comment]
jan I think what you suggest works for now.  Eventually though, and probably not before the conference, all this stuff spread over different ownerships needs to converge.

**Comment by tempire** [comment]
The Google apps thing sounds good, though we could also do something like
zen desk, though there's a charge to it. If we're using email, we have to
determine who's answering them.

**Comment by tempire** [comment]
I don't care what we do. 

The domain for mojoconf.com is already set up to receive email at a google apps account. Unless someone wants to set something else up, that's what we'll use.

**Comment by jhthorsen** [comment]
Google says "This domain name has already been used as an alias or domain", so i cannot set it up.

**Comment by jhthorsen** [comment]
That's weird. it worked the fifth time I tried.

@tempire: Can you add a TXT record with this content:

```
google-site-verification=Hgrq-zDWcbsbzsK0wTd_mCxgh7ovRQXo2dc19gbJRDs
```

Or add this meta tag to the index page:

```
<meta name="google-site-verification" content="Hgrq-zDWcbsbzsK0wTd_mCxgh7ovRQXo2dc19gbJRDs" />
```

**Comment by tempire** [comment]
meta tag added.

**Comment by jhthorsen** [comment]
Awesome! You can remove it now :-)

```
Great job, http://mojoconf.com/ is now verified!
```

**Comment by jhthorsen** [comment]
I don't understand that you have set the MX records. Sure you haven't just added CNAME?

```
$ dig mojoconf.com MX

; <<>> DiG 9.9.5-4.3ubuntu0.2-Ubuntu <<>> mojoconf.com MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33873
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mojoconf.com.          IN  MX

;; ANSWER SECTION:
mojoconf.com.       1800    IN  CNAME   simple.zombiedolphin.com.

;; AUTHORITY SECTION:
zombiedolphin.com.  300 IN  SOA ns1.dnsimple.com. admin.dnsimple.com. 1424911352 86400 7200 604800 300

;; Query time: 188 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Wed Mar 04 07:40:16 CET 2015
;; MSG SIZE  rcvd: 131
```

The MX records should be:

```
MX Server address   Priority
ASPMX.L.GOOGLE.COM. 1
ALT1.ASPMX.L.GOOGLE.COM.    5
ALT2.ASPMX.L.GOOGLE.COM.    5
ASPMX2.GOOGLEMAIL.COM.  10
ASPMX3.GOOGLEMAIL.COM.  10
```

**Comment by tempire** [comment]
Indeed. Something is wrong. I've sent a support request to the registrar.

**Comment by tempire** [comment]
The MX records are now reporting properly.

**Comment by jhthorsen** [comment]
This is not good:

```
The legacy free edition of Google Apps only supports domain aliases, not secondary domains.
```

I tried to set up an alias, but I'm not sure if it's working properly.

I'm all in on alternative solutions if anyone has one.

**Comment by tempire** [comment]
It should work just fine for our purposes; I set up aliases all the time. I
would have volunteered but I'm already using hello/help/support/etc for
other things.

I can take another look at my account (legacy also) and see if there's some
special setting I made to make it work.

**Comment by tempire** [comment]
I received the 2 test emails you sent.

**Comment by jhthorsen** [comment]
@tempire and @rpcme seems good with the email solution.

One important note: It's fine that people answer with their own email, but it's super important that they "reply to all" (including the hello@ email) so all of us get "notified" that the email has been handled.

@tempire: Please close this issue after you have updated `templates/partial/ask_question.html.ep` in MCT.git to send email to the new address.
