### ISSUE TITLE
mojoconf twitter account

### ISSUE THREAD

**Issue by tempire** [mojoconf/nyc-2015-06-05#9]
For this year and all the years ahead.

**Comment by tempire** [comment]
Created.

@mojoconf

**Comment by jhthorsen** [comment]
https://twitter.com/mojoconf

**Comment by jhthorsen** [comment]
@tempire: Can you add me and @marcusramberg as admins to the @mojoconf twitter account? Would like to post some updates now that we're doing http://oslo.pm/npw2018/
